
const phoneData=[
{name:"iPhone 16 Pro",brand:"APPLE",price:349999,ram:"8GB RAM",storage:"128GB",display:"6.3-inch OLED",camera:"48MP Pro Camera",battery:"Up to 27 hours",image:"https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=700&q=80"},
{name:"Galaxy S25 Ultra",brand:"SAMSUNG",price:389999,ram:"12GB RAM",storage:"256GB",display:"6.9-inch AMOLED",camera:"200MP Quad Camera",battery:"5000mAh",image:"https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=700&q=80"},
{name:"Google Pixel 9 Pro",brand:"GOOGLE",price:259999,ram:"16GB RAM",storage:"256GB",display:"6.3-inch OLED",camera:"50MP Triple Camera",battery:"4700mAh",image:"https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=700&q=80"},
{name:"OnePlus 13",brand:"ONEPLUS",price:219999,ram:"12GB RAM",storage:"256GB",display:"6.82-inch AMOLED",camera:"50MP Triple Camera",battery:"6000mAh",image:"https://images.unsplash.com/photo-1603899122634-f086ca5f5ddd?auto=format&fit=crop&w=700&q=80"},
{name:"Xiaomi 14T Pro",brand:"XIAOMI",price:189999,ram:"12GB RAM",storage:"512GB",display:"6.67-inch AMOLED",camera:"50MP Leica Camera",battery:"5000mAh",image:"https://images.unsplash.com/photo-1592286927505-1def25115558?auto=format&fit=crop&w=700&q=80"},
{name:"Nothing Phone (3)",brand:"NOTHING",price:179999,ram:"12GB RAM",storage:"256GB",display:"6.7-inch OLED",camera:"50MP Dual Camera",battery:"5150mAh",image:"https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?auto=format&fit=crop&w=700&q=80"}
];
const getStore=(k)=>JSON.parse(localStorage.getItem(k)||"[]"), setStore=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const money=n=>"Rs. "+Number(n).toLocaleString();
const toast=document.getElementById("toast"),toastMessage=document.getElementById("toastMessage");let toastTimeout;
function showToast(message){if(!toast||!toastMessage)return;toastMessage.textContent=message;toast.classList.add("show");clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>toast.classList.remove("show"),3000)}
function updateBadges(){const cart=getStore("mv_cart"),wish=getStore("mv_wishlist");document.querySelectorAll(".cart-count").forEach(x=>x.textContent=cart.reduce((s,x)=>s+(x.qty||1),0));document.querySelectorAll(".wishlist-count").forEach(x=>x.textContent=wish.length)}
document.addEventListener("DOMContentLoaded",()=>{
 updateBadges();
 const menuToggle=document.getElementById("menuToggle"),navMenu=document.getElementById("navMenu");
 if(menuToggle&&navMenu)menuToggle.addEventListener("click",()=>{navMenu.classList.toggle("active");const i=menuToggle.querySelector("i");i.classList.toggle("fa-bars");i.classList.toggle("fa-xmark")});
 document.querySelectorAll(".nav-menu a").forEach(link=>link.addEventListener("click",()=>{if(navMenu)navMenu.classList.remove("active")}));
 document.querySelectorAll(".add-cart").forEach(button=>button.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();const name=button.dataset.product;let cart=getStore("mv_cart");let item=cart.find(x=>x.name===name);if(item)item.qty++;else{let d=phoneData.find(x=>x.name===name)||{};cart.push({name,price:Number(button.dataset.price||d.price||0),image:button.dataset.image||d.image||"",qty:1})}setStore("mv_cart",cart);updateBadges();const old=button.innerHTML;button.innerHTML='<i class="fa-solid fa-check"></i> Added';setTimeout(()=>button.innerHTML=old,1000);showToast(name+" added to cart!")}));
 document.querySelectorAll(".product-heart").forEach(button=>button.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();let card=button.closest(".product-card"),name=card?.querySelector("h3")?.textContent||"";let w=getStore("mv_wishlist"),exists=w.includes(name);w=exists?w.filter(x=>x!==name):[...w,name];setStore("mv_wishlist",w);button.classList.toggle("active",!exists);button.querySelector("i").className=!exists?"fa-solid fa-heart":"fa-regular fa-heart";updateBadges();showToast(exists?"Removed from wishlist":"Added to wishlist!")}));
 const tabs=document.querySelectorAll(".tab"),products=document.querySelectorAll(".product-card");
 tabs.forEach(tab=>tab.addEventListener("click",()=>{tabs.forEach(t=>t.classList.remove("active"));tab.classList.add("active");products.forEach(p=>p.style.display=(tab.dataset.filter==="all"||p.dataset.category===tab.dataset.filter)?"block":"none")}));
 const searchInput=document.getElementById("phoneSearch"),searchBtn=document.getElementById("searchBtn");
 function performSearch(){if(!searchInput)return;const value=searchInput.value.trim();if(!value)return showToast("Please enter a phone or specification to search.");const productsSection=document.getElementById("products");if(productsSection)productsSection.scrollIntoView({behavior:"smooth"});const text=value.toLowerCase();products.forEach(p=>p.style.display=p.innerText.toLowerCase().includes(text)?"block":"none");showToast('Showing results for "'+value+'"')}
 if(searchBtn)searchBtn.addEventListener("click",performSearch);if(searchInput)searchInput.addEventListener("keydown",e=>{if(e.key==="Enter")performSearch()});
 document.querySelectorAll(".popular-searches button").forEach(b=>b.addEventListener("click",()=>{if(searchInput){searchInput.value=b.textContent.trim();performSearch()}}));
 const nf=document.getElementById("newsletterForm");if(nf)nf.addEventListener("submit",e=>{e.preventDefault();showToast("Successfully subscribed!");nf.reset()});
 document.querySelectorAll(".filter-panel input").forEach(i=>i.addEventListener("change",filterShop));
 const sort=document.getElementById("sortProducts");if(sort)sort.addEventListener("change",sortShop);
 initCompare();initDetail();renderCart();renderWishlist();initAccount();
});
function filterShop(){const brands=[...document.querySelectorAll(".filter-panel input[type=checkbox]:checked")].map(x=>x.value),price=document.querySelector(".filter-panel input[name=price]:checked")?.value||"all";let count=0;document.querySelectorAll("#productGrid .product-card").forEach(card=>{const data=phoneData.find(x=>x.name===card.querySelector("h3").textContent),cat=card.dataset.category;let ok=(!brands.length||brands.includes(cat))&&(price==="all"||(price==="under200"&&data.price<200000)||(price==="premium"&&data.price>=200000));card.style.display=ok?"block":"none";if(ok)count++});const rc=document.getElementById("resultCount");if(rc)rc.textContent=count}
function sortShop(){const grid=document.getElementById("productGrid"),mode=document.getElementById("sortProducts")?.value;if(!grid)return;[...grid.children].sort((a,b)=>{let pa=phoneData.find(x=>x.name===a.querySelector("h3").textContent).price,pb=phoneData.find(x=>x.name===b.querySelector("h3").textContent).price;return mode==="low"?pa-pb:mode==="high"?pb-pa:0}).forEach(x=>grid.appendChild(x))}
function initCompare(){const a=document.getElementById("compareA"),b=document.getElementById("compareB");if(!a||!b)return;phoneData.forEach((p,i)=>{a.add(new Option(p.name,p.name,i===0,i===0));b.add(new Option(p.name,p.name,i===1,i===1))});const render=()=>{let x=phoneData.find(p=>p.name===a.value),y=phoneData.find(p=>p.name===b.value);document.getElementById("comparisonResult").innerHTML=`<table class="comparison-table"><tr><th>Specification</th><th>${x.name}</th><th>${y.name}</th></tr>${["brand","price","ram","storage","display","camera","battery"].map(k=>`<tr><td>${k[0].toUpperCase()+k.slice(1)}</td><td>${k==="price"?money(x[k]):x[k]}</td><td>${k==="price"?money(y[k]):y[k]}</td></tr>`).join("")}</table>`};document.getElementById("compareBtn")?.addEventListener("click",render);render()}
function initDetail(){const box=document.getElementById("productDetail");if(!box)return;const name=new URLSearchParams(location.search).get("name")||phoneData[0].name,p=phoneData.find(x=>x.name===name)||phoneData[0];document.getElementById("crumbProduct").textContent=p.name;box.innerHTML=`<div class="detail-image"><img src="${p.image}" alt="${p.name}"></div><div class="detail-info"><p class="detail-brand">${p.brand}</p><h1>${p.name}</h1><div class="rating"><span class="stars">★★★★★</span><span>(96 reviews)</span></div><div class="detail-price">${money(p.price)}</div><p>Experience premium performance, a beautiful display and advanced camera technology in a smartphone built for everyday life.</p><div class="feature-list"><div><strong>RAM</strong><br>${p.ram}</div><div><strong>Storage</strong><br>${p.storage}</div><div><strong>Display</strong><br>${p.display}</div><div><strong>Camera</strong><br>${p.camera}</div><div><strong>Battery</strong><br>${p.battery}</div><div><strong>Warranty</strong><br>Official 1 Year</div></div><div class="detail-actions"><div class="quantity-control"><button id="qtyMinus">−</button><span id="qty">1</span><button id="qtyPlus">+</button></div><button class="btn btn-primary" id="detailAdd">Add to Cart <i class="fa-solid fa-bag-shopping"></i></button></div></div>`;let q=1;document.getElementById("qtyMinus").onclick=()=>{q=Math.max(1,q-1);document.getElementById("qty").textContent=q};document.getElementById("qtyPlus").onclick=()=>{q++;document.getElementById("qty").textContent=q};document.getElementById("detailAdd").onclick=()=>{let c=getStore("mv_cart"),i=c.find(x=>x.name===p.name);if(i)i.qty+=q;else c.push({name:p.name,price:p.price,image:p.image,qty:q});setStore("mv_cart",c);updateBadges();showToast("Added to cart!")}}
function renderCart(){const box=document.getElementById("cartItems");if(!box)return;let c=getStore("mv_cart"),sub=c.reduce((s,x)=>s+x.price*x.qty,0);document.getElementById("cartSubtotal").textContent=money(sub);document.getElementById("cartTotal").textContent=money(sub);box.innerHTML=c.length?c.map((x,i)=>`<div class="cart-row"><img src="${x.image}" alt="${x.name}"><div><h3>${x.name}</h3><p>${money(x.price)} × ${x.qty}</p><button class="remove-btn" data-i="${i}">Remove</button></div><div class="price"><strong>${money(x.price*x.qty)}</strong></div></div>`).join(""):`<div class="empty-card"><i class="fa-solid fa-bag-shopping"></i><h2>Your cart is empty</h2><p>Add a smartphone to start your order.</p><a class="btn btn-primary" href="shop.html">Shop Now</a></div>`;box.querySelectorAll(".remove-btn").forEach(b=>b.onclick=()=>{c.splice(b.dataset.i,1);setStore("mv_cart",c);updateBadges();renderCart()});document.getElementById("checkoutBtn")?.addEventListener("click",()=>showToast(c.length?"Demo checkout completed!":"Your cart is empty."))}
function renderWishlist(){const box=document.getElementById("wishlistPage");if(!box)return;let names=getStore("mv_wishlist"),items=phoneData.filter(p=>names.includes(p.name));box.innerHTML=items.length?`<div class="product-grid">${items.map(p=>`<article class="product-card"><a href="product.html?name=${encodeURIComponent(p.name)}" class="product-image"><img src="${p.image}" alt="${p.name}"></a><div class="product-info"><p class="product-brand">${p.brand}</p><h3>${p.name}</h3><div class="product-bottom"><div class="price"><strong>${money(p.price)}</strong></div><button class="add-cart" data-product="${p.name}" data-price="${p.price}" data-image="${p.image}">Add</button></div></div></article>`).join("")}</div>`:`<div class="empty-card"><i class="fa-regular fa-heart"></i><h2>Your wishlist is empty</h2><p>Save phones here and revisit them later.</p><a class="btn btn-primary" href="shop.html">Browse Phones</a></div>`;box.querySelectorAll(".add-cart").forEach(b=>b.addEventListener("click",()=>{let c=getStore("mv_cart"),i=c.find(x=>x.name===b.dataset.product);if(i)i.qty++;else c.push({name:b.dataset.product,price:+b.dataset.price,image:b.dataset.image,qty:1});setStore("mv_cart",c);updateBadges();showToast("Added to cart!")}))}
function initAccount(){const saved=JSON.parse(localStorage.getItem("mv_profile")||"{}");["firstName","lastName","accountEmail","phone","address"].forEach(id=>{let e=document.getElementById(id);if(e)e.value=saved[id]||""});document.querySelectorAll(".account-tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".account-tabs button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".account-pane").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.pane).classList.add("active")});["profileForm","addressForm"].forEach(id=>document.getElementById(id)?.addEventListener("submit",e=>{e.preventDefault();let data=JSON.parse(localStorage.getItem("mv_profile")||"{}");["firstName","lastName","accountEmail","phone","address"].forEach(k=>{let el=document.getElementById(k);if(el)data[k]=el.value});localStorage.setItem("mv_profile",JSON.stringify(data));showToast("Saved successfully!")}))}
